# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shawn's Site
email: N/A
description: > # this means to ignore newlines until "baseurl:"
  Shawn's website where he posts all his stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shawn11564.github.io" # the base hostname & protocol for your site
twitter_username: Shawn11564
github_username:  Shawn11464

# Build settings
markdown: kramdown
